-- ============================================================================
-- 12_schema_execution.sql
-- ----------------------------------------------------------------------------
-- Durable, idempotent, auditable order store for the Execution engine
-- (feature-execution-engine, Phase 1). Lives in its OWN database
-- ``db_execution`` (created in 01_create_databases.sql), inside an
-- ``execution`` schema, mirroring the db_market_data precedent so the order
-- store is independently owned and decoupled from db_gateway / strategy DBs.
--
-- The standalone ``quant-execution-engine`` service is the eventual sole
-- writer (Phase 2). Phase 1 ships schema only — no engine code, no adapters.
-- Strategies and the gateway never write ``execution.*``.
--
-- Conventions:
--   * PLAIN tables, NOT hypertables, and NO timescaledb extension here.
--     This is the low-volume real-money order-command plane: tens of rows a
--     day, not tick data. ``fills`` and ``order_events`` carry FOREIGN KEYs
--     to ``orders`` and hypertables cannot be FK targets; chunking,
--     compression and retention machinery buy nothing and would actively
--     endanger audit rows.
--   * Enums are TEXT + CHECK constraints (the 10_schema_market_data.sql
--     precedent), not Postgres ENUM types — idempotent under re-run without
--     DO-block guards, evolvable with DROP/ADD CONSTRAINT, and violations
--     raise plain check_violation (23514) errors that tests assert directly.
--     The value sets are the FROZEN NormalizedOrder contract (Phase 0 ADR,
--     ACCEPTED 2026-06-10).
--   * ``client_order_id`` is TEXT, not uuid: ADR §A pins UUIDv4 generated by
--     the client and "format-validated at the boundary … stored, compared,
--     never parsed", with ULID / UUIDv7 / Snowflake as acceptable drop-in
--     upgrades — a ``uuid`` column would forbid exactly those upgrades. Only
--     a length sanity CHECK applies here; format validation is the engine
--     boundary's job (Phase 2).
--   * Prices NUMERIC(18, 6) (money is Decimal-on-wire, never float);
--     quantities BIGINT (the frozen contract pins ``quantity: int`` — SET
--     shares and TFEX contracts are integral).
--   * All timestamps TIMESTAMPTZ, stored UTC (display Asia/Bangkok at the
--     edge). ``created_at``/``updated_at`` are DB row times; venue execution
--     times live on ``fills.exec_ts``.
--   * The FROZEN 9-state order machine (quant-execution-engine
--     .claude/knowledge/order-state-machine.md) is enforced by a BEFORE
--     trigger encoding EXACTLY the 13 frozen edges. Edges the frozen graph
--     does not contain (a venue rejecting a cancel, fills arriving while
--     PENDING_CANCEL, PENDING_REPLACE -> CANCELLED for Liberator's
--     cancel+replace amend path) are deliberately NOT encoded; amending the
--     graph requires an ADR amendment first, then a follow-up migration.
--   * ``order_events`` is append-only and trigger-written: every INSERT /
--     legal transition on ``orders`` auto-appends one audit row;
--     UPDATE/DELETE/TRUNCATE on ``order_events`` raise. The DB enforces the
--     "every transition appends an immutable audit row" invariant — no app
--     code required. The PENDING_NEW -> NEW audit row snapshots
--     ``broker_order_id`` atomically with the transition (ADR §B).
--   * Grants: only the ``postgres`` superuser exists today, so no GRANTs are
--     issued. When Phase 2 adds a service role (``execution_engine``), grant
--     it SELECT/INSERT/UPDATE on orders and SELECT/INSERT on fills /
--     order_events — nothing else; strategies and the gateway get no write
--     grant on ``execution.*``. The triggers remain the backstop either way.
--   * ``reject_reason`` (nullable TEXT) was added in Phase 2 — the
--     Phase-1-sanctioned ALTER: the engine persists the adapter/venue reject
--     reason durably on the REJECTED row (real-money audit must not live in a
--     cache). ``metadata`` stays deliberately omitted (opaque strategy tags,
--     never venue-sent; the engine consumes it in-flight only).
--   * Fully idempotent: re-running this script (or container init) is a
--     no-op (IF NOT EXISTS / CREATE OR REPLACE; PG14+ has
--     CREATE OR REPLACE TRIGGER and the stack runs latest-pg16).
--
-- Rollback (no migration framework — init-scripts only): this schema is
-- self-contained in its own database. To drop it entirely:
--     \c db_execution
--     DROP SCHEMA IF EXISTS execution CASCADE;
--   -- then, connected to another DB (e.g. postgres):
--     DROP DATABASE IF EXISTS db_execution;
-- A fresh container volume re-applies this script from scratch.
-- ============================================================================

\connect db_execution

CREATE SCHEMA IF NOT EXISTS execution;

-- ---------------------------------------------------------------------------
-- execution.orders — one row per client order. The PRIMARY KEY on
-- ``client_order_id`` IS the idempotency constraint (ADR §A): a re-submitted
-- order collides here and the engine returns the prior result.
-- ``broker_order_id`` is venue-assigned and NULL until ack (ADR §B).
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS execution.orders (
    client_order_id TEXT           NOT NULL,
    broker          TEXT           NOT NULL
        CHECK (broker IN ('sim', 'liberator', 'settrade')),
    broker_order_id TEXT,
    account         TEXT           NOT NULL,
    symbol          TEXT           NOT NULL,
    market          TEXT           NOT NULL CHECK (market IN ('SET', 'TFEX')),
    side            TEXT           NOT NULL CHECK (side IN ('BUY', 'SELL')),
    order_type      TEXT           NOT NULL
        CHECK (order_type IN ('MARKET', 'LIMIT', 'STOP', 'STOP_LIMIT',
                              'ICEBERG', 'MTL', 'ATO', 'ATC')),
    price           NUMERIC(18, 6) CHECK (price IS NULL OR price > 0),
    stop_price      NUMERIC(18, 6) CHECK (stop_price IS NULL OR stop_price > 0),
    quantity        BIGINT         NOT NULL CHECK (quantity > 0),
    display_qty     BIGINT,
    tif             TEXT           NOT NULL
        CHECK (tif IN ('DAY', 'IOC', 'FOK', 'GTC')),
    position_effect TEXT
        CHECK (position_effect IS NULL OR position_effect IN ('OPEN', 'CLOSE')),
    status          TEXT           NOT NULL DEFAULT 'PENDING_NEW'
        CHECK (status IN ('PENDING_NEW', 'NEW', 'PARTIALLY_FILLED', 'FILLED',
                          'PENDING_CANCEL', 'PENDING_REPLACE',
                          'CANCELLED', 'REJECTED', 'EXPIRED')),
    reject_reason   TEXT,
    created_at      TIMESTAMPTZ    NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ    NOT NULL DEFAULT now(),
    CONSTRAINT pk_orders PRIMARY KEY (client_order_id),
    -- ADR §A: the id is opaque — only a sanity bound, no format/scheme encoded.
    CONSTRAINT ck_orders_client_order_id_len
        CHECK (char_length(client_order_id) BETWEEN 8 AND 64),
    -- Frozen-contract cross-field rules:
    CONSTRAINT ck_orders_display_qty
        CHECK (display_qty IS NULL OR (display_qty > 0 AND display_qty <= quantity)),
    CONSTRAINT ck_orders_price_required
        CHECK (order_type NOT IN ('LIMIT', 'STOP_LIMIT') OR price IS NOT NULL),
    CONSTRAINT ck_orders_stop_price_required
        CHECK (order_type NOT IN ('STOP', 'STOP_LIMIT') OR stop_price IS NOT NULL),
    CONSTRAINT ck_orders_position_effect_tfex_only
        CHECK (position_effect IS NULL OR market = 'TFEX')
);

-- Phase 2 addition (idempotent on databases created before it existed):
-- CREATE TABLE IF NOT EXISTS above does not add columns to a live table.
ALTER TABLE execution.orders ADD COLUMN IF NOT EXISTS reject_reason TEXT;

-- Venue -> local lookup once an ack has assigned a broker_order_id. Partial:
-- PENDING_NEW rows have no venue id; the lookup always carries a concrete id.
-- NOT unique: venue order numbers are venue-/day-scoped and may recycle.
CREATE INDEX IF NOT EXISTS idx_orders_broker_order_id
    ON execution.orders (broker, broker_order_id)
    WHERE broker_order_id IS NOT NULL;

-- ADR §B reconciliation fuzzy-match: (account, symbol, side, qty) within
-- ±5 s of the persisted submit timestamp; created_at last for the range scan.
CREATE INDEX IF NOT EXISTS idx_orders_reconcile
    ON execution.orders (account, symbol, side, quantity, created_at);

-- ---------------------------------------------------------------------------
-- execution.fills — partial/total executions, one row per fill event.
-- Identity PK (single writer, compact, insertion-ordered).
-- UNIQUE (client_order_id, broker_fill_id) dedupes at-least-once venue fill
-- delivery; NULL broker_fill_id rows are NOT deduped (Postgres treats NULLs
-- as distinct) — adapters must supply a fill id (SimAdapter synthesises one).
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS execution.fills (
    fill_id         BIGINT         GENERATED ALWAYS AS IDENTITY,
    client_order_id TEXT           NOT NULL
        REFERENCES execution.orders (client_order_id),
    broker_fill_id  TEXT,
    price           NUMERIC(18, 6) NOT NULL CHECK (price > 0),
    quantity        BIGINT         NOT NULL CHECK (quantity > 0),
    exec_ts         TIMESTAMPTZ    NOT NULL,
    created_at      TIMESTAMPTZ    NOT NULL DEFAULT now(),
    CONSTRAINT pk_fills PRIMARY KEY (fill_id),
    CONSTRAINT uq_fills_order_broker_fill UNIQUE (client_order_id, broker_fill_id)
);
-- No extra per-order index: uq_fills_order_broker_fill leads on
-- client_order_id and covers the FK/per-order lookup.

-- ---------------------------------------------------------------------------
-- execution.order_events — append-only audit log; one row per transition,
-- auto-appended by trigger (INSERT writes the NULL -> PENDING_NEW birth row).
-- FK side effect: every order has >= 1 event, so orders can never be deleted
-- — the audit chain protects its subject.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS execution.order_events (
    event_id        BIGINT      GENERATED ALWAYS AS IDENTITY,
    client_order_id TEXT        NOT NULL
        REFERENCES execution.orders (client_order_id),
    from_status     TEXT
        CHECK (from_status IS NULL OR
               from_status IN ('PENDING_NEW', 'NEW', 'PARTIALLY_FILLED', 'FILLED',
                               'PENDING_CANCEL', 'PENDING_REPLACE',
                               'CANCELLED', 'REJECTED', 'EXPIRED')),
    to_status       TEXT        NOT NULL
        CHECK (to_status IN ('PENDING_NEW', 'NEW', 'PARTIALLY_FILLED', 'FILLED',
                             'PENDING_CANCEL', 'PENDING_REPLACE',
                             'CANCELLED', 'REJECTED', 'EXPIRED')),
    event           JSONB,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT pk_order_events PRIMARY KEY (event_id)
);

-- Audit-read path: all events for an order, in total order (event_id is
-- monotonic even when created_at ties inside one transaction).
CREATE INDEX IF NOT EXISTS idx_order_events_order
    ON execution.order_events (client_order_id, event_id);

-- ---------------------------------------------------------------------------
-- Trigger 1 — entry-state + legal-transition guard + updated_at upkeep.
-- Encodes EXACTLY the 13 frozen edges of order-state-machine.md (Phase 0).
-- Terminal immutability falls out of the edge list (no terminal source edge).
-- Same-status UPDATEs (e.g. a second partial fill) are allowed and append no
-- event — fills are audited in execution.fills.
-- ERRCODE 23514 (check_violation) so asyncpg raises CheckViolationError,
-- matching how column CHECK rejections already surface in the infra suite.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION execution.orders_guard()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    legal CONSTANT TEXT[] := ARRAY[
        'PENDING_NEW->NEW',
        'PENDING_NEW->REJECTED',
        'NEW->PARTIALLY_FILLED',
        'NEW->FILLED',
        'NEW->EXPIRED',
        'NEW->PENDING_CANCEL',
        'NEW->PENDING_REPLACE',
        'PARTIALLY_FILLED->FILLED',
        'PARTIALLY_FILLED->EXPIRED',
        'PARTIALLY_FILLED->PENDING_CANCEL',
        'PARTIALLY_FILLED->PENDING_REPLACE',
        'PENDING_CANCEL->CANCELLED',
        'PENDING_REPLACE->NEW'
    ];
BEGIN
    IF TG_OP = 'INSERT' THEN
        IF NEW.status <> 'PENDING_NEW' THEN
            RAISE EXCEPTION
                'orders must enter at PENDING_NEW (got %)', NEW.status
                USING ERRCODE = 'check_violation';
        END IF;
        RETURN NEW;
    END IF;
    -- TG_OP = 'UPDATE'
    IF NEW.status IS DISTINCT FROM OLD.status
       AND NOT (OLD.status || '->' || NEW.status) = ANY (legal) THEN
        RAISE EXCEPTION
            'illegal order status transition % -> % (client_order_id=%)',
            OLD.status, NEW.status, OLD.client_order_id
            USING ERRCODE = 'check_violation';
    END IF;
    NEW.updated_at := now();
    RETURN NEW;
END;
$$;

CREATE OR REPLACE TRIGGER trg_orders_guard
    BEFORE INSERT OR UPDATE ON execution.orders
    FOR EACH ROW EXECUTE FUNCTION execution.orders_guard();

-- ---------------------------------------------------------------------------
-- Trigger 2 — auto-append the audit row ("every transition appends an
-- immutable audit row" is DB-enforced, not app-supplied). The payload
-- snapshots the §B-critical fields: the PENDING_NEW -> NEW row records the
-- broker_order_id atomically with the transition; the PENDING_REPLACE -> NEW
-- row records the amended price/quantity. Price as text (Decimal-as-string).
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION execution.orders_append_event()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF TG_OP = 'INSERT' OR NEW.status IS DISTINCT FROM OLD.status THEN
        INSERT INTO execution.order_events (client_order_id, from_status, to_status, event)
        VALUES (
            NEW.client_order_id,
            CASE WHEN TG_OP = 'INSERT' THEN NULL ELSE OLD.status END,
            NEW.status,
            jsonb_build_object(
                'broker_order_id', NEW.broker_order_id,
                'price',           NEW.price::TEXT,
                'quantity',        NEW.quantity
            )
        );
    END IF;
    RETURN NULL;  -- AFTER trigger
END;
$$;

CREATE OR REPLACE TRIGGER trg_orders_append_event
    AFTER INSERT OR UPDATE ON execution.orders
    FOR EACH ROW EXECUTE FUNCTION execution.orders_append_event();

-- ---------------------------------------------------------------------------
-- Trigger 3 — order_events is append-only. Statement-level (fires even for
-- zero-row statements); TRUNCATE blocked too. Grants cannot enforce anything
-- while only the postgres superuser exists, so the trigger IS the
-- enforcement. Default ERRCODE P0001 -> asyncpg RaiseError.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION execution.order_events_block_mutation()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION 'execution.order_events is append-only (% blocked)', TG_OP;
END;
$$;

CREATE OR REPLACE TRIGGER trg_order_events_no_update_delete
    BEFORE UPDATE OR DELETE ON execution.order_events
    FOR EACH STATEMENT EXECUTE FUNCTION execution.order_events_block_mutation();

CREATE OR REPLACE TRIGGER trg_order_events_no_truncate
    BEFORE TRUNCATE ON execution.order_events
    FOR EACH STATEMENT EXECUTE FUNCTION execution.order_events_block_mutation();
