-- ============================================================================
-- 12_schema_execution.sql
-- ----------------------------------------------------------------------------
-- Durable, idempotent, auditable order store for the Execution engine
-- (feature-execution-engine, Phase 1). Lives in its OWN database
-- ``db_execution`` (created in 01_create_databases.sql), inside an
-- ``execution`` schema, mirroring the db_market_data precedent so the order
-- store is independently owned and decoupled from db_gateway / strategy DBs.
--
-- The standalone ``quant-execution-engine`` service is the eventual sole
-- writer (Phase 2). Phase 1 ships schema only — no engine code, no adapters.
-- Strategies and the gateway never write ``execution.*``.
--
-- Conventions:
--   * PLAIN tables, NOT hypertables, and NO timescaledb extension here.
--     This is the low-volume real-money order-command plane: tens of rows a
--     day, not tick data. ``fills`` and ``order_events`` carry FOREIGN KEYs
--     to ``orders`` and hypertables cannot be FK targets; chunking,
--     compression and retention machinery buy nothing and would actively
--     endanger audit rows.
--   * Enums are TEXT + CHECK constraints (the 10_schema_market_data.sql
--     precedent), not Postgres ENUM types — idempotent under re-run without
--     DO-block guards, evolvable with DROP/ADD CONSTRAINT, and violations
--     raise plain check_violation (23514) errors that tests assert directly.
--     The value sets are the FROZEN NormalizedOrder contract (Phase 0 ADR,
--     ACCEPTED 2026-06-10).
--   * ``client_order_id`` is TEXT, not uuid: ADR §A pins UUIDv4 generated by
--     the client and "format-validated at the boundary … stored, compared,
--     never parsed", with ULID / UUIDv7 / Snowflake as acceptable drop-in
--     upgrades — a ``uuid`` column would forbid exactly those upgrades. Only
--     a length sanity CHECK applies here; format validation is the engine
--     boundary's job (Phase 2).
--   * Prices NUMERIC(18, 6) (money is Decimal-on-wire, never float);
--     quantities BIGINT (the frozen contract pins ``quantity: int`` — SET
--     shares and TFEX contracts are integral).
--   * All timestamps TIMESTAMPTZ, stored UTC (display Asia/Bangkok at the
--     edge). ``created_at``/``updated_at`` are DB row times; venue execution
--     times live on ``fills.exec_ts``.
--   * The FROZEN 9-state order machine (quant-execution-engine
--     .claude/knowledge/order-state-machine.md) is enforced by a BEFORE
--     trigger encoding EXACTLY the 13 frozen edges. Edges the frozen graph
--     does not contain (a venue rejecting a cancel, fills arriving while
--     PENDING_CANCEL, PENDING_REPLACE -> CANCELLED for Liberator's
--     cancel+replace amend path) are deliberately NOT encoded; amending the
--     graph requires an ADR amendment first, then a follow-up migration.
--   * ``order_events`` is append-only and trigger-written: every INSERT /
--     legal transition on ``orders`` auto-appends one audit row;
--     UPDATE/DELETE/TRUNCATE on ``order_events`` raise. The DB enforces the
--     "every transition appends an immutable audit row" invariant — no app
--     code required. The PENDING_NEW -> NEW audit row snapshots
--     ``broker_order_id`` atomically with the transition (ADR §B).
--   * Grants: only the ``postgres`` superuser exists today, so no GRANTs are
--     issued. When Phase 2 adds a service role (``execution_engine``), grant
--     it SELECT/INSERT/UPDATE on orders and SELECT/INSERT on fills /
--     order_events — nothing else; strategies and the gateway get no write
--     grant on ``execution.*``. The triggers remain the backstop either way.
--   * ``reject_reason`` (nullable TEXT) was added in Phase 2 — the
--     Phase-1-sanctioned ALTER: the engine persists the adapter/venue reject
--     reason durably on the REJECTED row (real-money audit must not live in a
--     cache). ``metadata`` stays deliberately omitted (opaque strategy tags,
--     never venue-sent; the engine consumes it in-flight only).
--   * Fully idempotent: re-running this script (or container init) is a
--     no-op (IF NOT EXISTS / CREATE OR REPLACE; PG14+ has
--     CREATE OR REPLACE TRIGGER and the stack runs latest-pg16).
--
-- Rollback (no migration framework — init-scripts only): this schema is
-- self-contained in its own database. To drop it entirely:
--     \c db_execution
--     DROP SCHEMA IF EXISTS execution CASCADE;
--   -- then, connected to another DB (e.g. postgres):
--     DROP DATABASE IF EXISTS db_execution;
-- A fresh container volume re-applies this script from scratch.
-- ============================================================================

\connect db_execution

CREATE SCHEMA IF NOT EXISTS execution;

-- ---------------------------------------------------------------------------
-- execution.orders — one row per client order. The PRIMARY KEY on
-- ``client_order_id`` IS the idempotency constraint (ADR §A): a re-submitted
-- order collides here and the engine returns the prior result.
-- ``broker_order_id`` is venue-assigned and NULL until ack (ADR §B).
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS execution.orders (
    client_order_id TEXT           NOT NULL,
    broker          TEXT           NOT NULL
        -- ⚠️ SUPERSEDED by 25_execution_broker_streaming_pro.sql: 'settrade' was
        -- removed from the engine 2026-07-18 and 'streaming_pro' replaced it.
        -- This line is the Phase-0 original, kept so the file still reads as
        -- written; 25_* is the live constraint. Do not re-derive it from here.
        CHECK (broker IN ('sim', 'liberator', 'settrade')),
    broker_order_id TEXT,
    account         TEXT           NOT NULL,
    symbol          TEXT           NOT NULL,
    market          TEXT           NOT NULL CHECK (market IN ('SET', 'TFEX')),
    side            TEXT           NOT NULL CHECK (side IN ('BUY', 'SELL')),
    order_type      TEXT           NOT NULL
        CHECK (order_type IN ('MARKET', 'LIMIT', 'STOP', 'STOP_LIMIT',
                              'ICEBERG', 'MTL', 'ATO', 'ATC')),
    price           NUMERIC(18, 6) CHECK (price IS NULL OR price > 0),
    stop_price      NUMERIC(18, 6) CHECK (stop_price IS NULL OR stop_price > 0),
    quantity        BIGINT         NOT NULL CHECK (quantity > 0),
    display_qty     BIGINT,
    tif             TEXT           NOT NULL
        CHECK (tif IN ('DAY', 'IOC', 'FOK', 'GTC')),
    position_effect TEXT
        CHECK (position_effect IS NULL OR position_effect IN ('OPEN', 'CLOSE')),
    status          TEXT           NOT NULL DEFAULT 'PENDING_NEW'
        CHECK (status IN ('PENDING_NEW', 'NEW', 'PARTIALLY_FILLED', 'FILLED',
                          'PENDING_CANCEL', 'PENDING_REPLACE',
                          'CANCELLED', 'REJECTED', 'EXPIRED')),
    reject_reason   TEXT,
    created_at      TIMESTAMPTZ    NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ    NOT NULL DEFAULT now(),
    CONSTRAINT pk_orders PRIMARY KEY (client_order_id),
    -- ADR §A: the id is opaque — only a sanity bound, no format/scheme encoded.
    CONSTRAINT ck_orders_client_order_id_len
        CHECK (char_length(client_order_id) BETWEEN 8 AND 64),
    -- Frozen-contract cross-field rules:
    CONSTRAINT ck_orders_display_qty
        CHECK (display_qty IS NULL OR (display_qty > 0 AND display_qty <= quantity)),
    CONSTRAINT ck_orders_price_required
        CHECK (order_type NOT IN ('LIMIT', 'STOP_LIMIT') OR price IS NOT NULL),
    CONSTRAINT ck_orders_stop_price_required
        CHECK (order_type NOT IN ('STOP', 'STOP_LIMIT') OR stop_price IS NOT NULL),
    CONSTRAINT ck_orders_position_effect_tfex_only
        CHECK (position_effect IS NULL OR market = 'TFEX')
);

-- Phase 2 addition (idempotent on databases created before it existed):
-- CREATE TABLE IF NOT EXISTS above does not add columns to a live table.
ALTER TABLE execution.orders ADD COLUMN IF NOT EXISTS reject_reason TEXT;

-- Venue -> local lookup once an ack has assigned a broker_order_id. Partial:
-- PENDING_NEW rows have no venue id; the lookup always carries a concrete id.
-- NOT unique: venue order numbers are venue-/day-scoped and may recycle.
CREATE INDEX IF NOT EXISTS idx_orders_broker_order_id
    ON execution.orders (broker, broker_order_id)
    WHERE broker_order_id IS NOT NULL;

-- ADR §B reconciliation fuzzy-match: (account, symbol, side, qty) within
-- ±5 s of the persisted submit timestamp; created_at last for the range scan.
CREATE INDEX IF NOT EXISTS idx_orders_reconcile
    ON execution.orders (account, symbol, side, quantity, created_at);

-- ---------------------------------------------------------------------------
-- execution.fills — partial/total executions, one row per fill event.
-- Identity PK (single writer, compact, insertion-ordered).
-- UNIQUE (client_order_id, broker_fill_id) dedupes at-least-once venue fill
-- delivery; NULL broker_fill_id rows are NOT deduped (Postgres treats NULLs
-- as distinct) — adapters must supply a fill id (SimAdapter synthesises one).
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS execution.fills (
    fill_id         BIGINT         GENERATED ALWAYS AS IDENTITY,
    client_order_id TEXT           NOT NULL
        REFERENCES execution.orders (client_order_id),
    broker_fill_id  TEXT,
    price           NUMERIC(18, 6) NOT NULL CHECK (price > 0),
    quantity        BIGINT         NOT NULL CHECK (quantity > 0),
    exec_ts         TIMESTAMPTZ    NOT NULL,
    created_at      TIMESTAMPTZ    NOT NULL DEFAULT now(),
    CONSTRAINT pk_fills PRIMARY KEY (fill_id),
    CONSTRAINT uq_fills_order_broker_fill UNIQUE (client_order_id, broker_fill_id)
);
-- No extra per-order index: uq_fills_order_broker_fill leads on
-- client_order_id and covers the FK/per-order lookup.

-- ---------------------------------------------------------------------------
-- execution.order_events — append-only audit log; one row per transition,
-- auto-appended by trigger (INSERT writes the NULL -> PENDING_NEW birth row).
-- FK side effect: every order has >= 1 event, so orders can never be deleted
-- — the audit chain protects its subject.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS execution.order_events (
    event_id        BIGINT      GENERATED ALWAYS AS IDENTITY,
    client_order_id TEXT        NOT NULL
        REFERENCES execution.orders (client_order_id),
    from_status     TEXT
        CHECK (from_status IS NULL OR
               from_status IN ('PENDING_NEW', 'NEW', 'PARTIALLY_FILLED', 'FILLED',
                               'PENDING_CANCEL', 'PENDING_REPLACE',
                               'CANCELLED', 'REJECTED', 'EXPIRED')),
    to_status       TEXT        NOT NULL
        CHECK (to_status IN ('PENDING_NEW', 'NEW', 'PARTIALLY_FILLED', 'FILLED',
                             'PENDING_CANCEL', 'PENDING_REPLACE',
                             'CANCELLED', 'REJECTED', 'EXPIRED')),
    event           JSONB,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT pk_order_events PRIMARY KEY (event_id)
);

-- Audit-read path: all events for an order, in total order (event_id is
-- monotonic even when created_at ties inside one transaction).
CREATE INDEX IF NOT EXISTS idx_order_events_order
    ON execution.order_events (client_order_id, event_id);

-- ---------------------------------------------------------------------------
-- Trigger 1 — entry-state + legal-transition guard + updated_at upkeep.
-- Encodes EXACTLY the 13 frozen edges of order-state-machine.md (Phase 0).
-- Terminal immutability falls out of the edge list (no terminal source edge).
-- Same-status UPDATEs (e.g. a second partial fill) are allowed and append no
-- event — fills are audited in execution.fills.
-- ERRCODE 23514 (check_violation) so asyncpg raises CheckViolationError,
-- matching how column CHECK rejections already surface in the infra suite.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION execution.orders_guard()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    legal CONSTANT TEXT[] := ARRAY[
        'PENDING_NEW->NEW',
        'PENDING_NEW->REJECTED',
        'NEW->PARTIALLY_FILLED',
        'NEW->FILLED',
        'NEW->EXPIRED',
        'NEW->PENDING_CANCEL',
        'NEW->PENDING_REPLACE',
        'PARTIALLY_FILLED->FILLED',
        'PARTIALLY_FILLED->EXPIRED',
        'PARTIALLY_FILLED->PENDING_CANCEL',
        'PARTIALLY_FILLED->PENDING_REPLACE',
        'PENDING_CANCEL->CANCELLED',
        'PENDING_REPLACE->NEW'
    ];
BEGIN
    IF TG_OP = 'INSERT' THEN
        IF NEW.status <> 'PENDING_NEW' THEN
            RAISE EXCEPTION
                'orders must enter at PENDING_NEW (got %)', NEW.status
                USING ERRCODE = 'check_violation';
        END IF;
        RETURN NEW;
    END IF;
    -- TG_OP = 'UPDATE'
    IF NEW.status IS DISTINCT FROM OLD.status
       AND NOT (OLD.status || '->' || NEW.status) = ANY (legal) THEN
        RAISE EXCEPTION
            'illegal order status transition % -> % (client_order_id=%)',
            OLD.status, NEW.status, OLD.client_order_id
            USING ERRCODE = 'check_violation';
    END IF;
    NEW.updated_at := now();
    RETURN NEW;
END;
$$;

CREATE OR REPLACE TRIGGER trg_orders_guard
    BEFORE INSERT OR UPDATE ON execution.orders
    FOR EACH ROW EXECUTE FUNCTION execution.orders_guard();

-- ---------------------------------------------------------------------------
-- Trigger 2 — auto-append the audit row ("every transition appends an
-- immutable audit row" is DB-enforced, not app-supplied). The payload
-- snapshots the §B-critical fields: the PENDING_NEW -> NEW row records the
-- broker_order_id atomically with the transition; the PENDING_REPLACE -> NEW
-- row records the amended price/quantity. Price as text (Decimal-as-string).
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION execution.orders_append_event()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF TG_OP = 'INSERT' OR NEW.status IS DISTINCT FROM OLD.status THEN
        INSERT INTO execution.order_events (client_order_id, from_status, to_status, event)
        VALUES (
            NEW.client_order_id,
            CASE WHEN TG_OP = 'INSERT' THEN NULL ELSE OLD.status END,
            NEW.status,
            jsonb_build_object(
                'broker_order_id', NEW.broker_order_id,
                'price',           NEW.price::TEXT,
                'quantity',        NEW.quantity
            )
        );
    END IF;
    RETURN NULL;  -- AFTER trigger
END;
$$;

CREATE OR REPLACE TRIGGER trg_orders_append_event
    AFTER INSERT OR UPDATE ON execution.orders
    FOR EACH ROW EXECUTE FUNCTION execution.orders_append_event();

-- ---------------------------------------------------------------------------
-- Trigger 3 — order_events is append-only. Statement-level (fires even for
-- zero-row statements); TRUNCATE blocked too. Grants cannot enforce anything
-- while only the postgres superuser exists, so the trigger IS the
-- enforcement. Default ERRCODE P0001 -> asyncpg RaiseError.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION execution.order_events_block_mutation()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION 'execution.order_events is append-only (% blocked)', TG_OP;
END;
$$;

CREATE OR REPLACE TRIGGER trg_order_events_no_update_delete
    BEFORE UPDATE OR DELETE ON execution.order_events
    FOR EACH STATEMENT EXECUTE FUNCTION execution.order_events_block_mutation();

CREATE OR REPLACE TRIGGER trg_order_events_no_truncate
    BEFORE TRUNCATE ON execution.order_events
    FOR EACH STATEMENT EXECUTE FUNCTION execution.order_events_block_mutation();

-- ---------------------------------------------------------------------------
-- Service-role grants (Phase 2 — the least-privilege block the Phase-1 header
-- promised). ``quant`` is the shared service role this stack's engines connect
-- as (the marketdata-engine precedent); created here if absent with the same
-- placeholder password the compose files ship — operators MUST override it
-- per machine (ALTER ROLE quant PASSWORD ...) outside the repo.
--
--   * orders:        SELECT, INSERT, UPDATE  (the lifecycle writer)
--   * fills:         SELECT, INSERT          (append-only by privilege)
--   * order_events:  SELECT, INSERT — INSERT is REQUIRED because the audit
--     trigger runs with INVOKER rights: the engine's INSERT/UPDATE on orders
--     fires orders_append_event, which inserts the audit row AS the engine
--     role. Append-only still holds: no UPDATE/DELETE granted, and the
--     block-mutation triggers reject them for every role anyway.
--   * sequences:     USAGE for the identity columns (fill_id / event_id).
--   * No DELETE anywhere; strategies and the gateway get NO grant at all.
-- ---------------------------------------------------------------------------
DO $$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'quant') THEN
        CREATE ROLE quant LOGIN PASSWORD 'quant';
    END IF;
END $$;

GRANT USAGE ON SCHEMA execution TO quant;
GRANT SELECT, INSERT, UPDATE ON execution.orders TO quant;
GRANT SELECT, INSERT ON execution.fills TO quant;
GRANT SELECT, INSERT ON execution.order_events TO quant;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA execution TO quant;
-- ⚠️ NOT EXHAUSTIVE. Tables added after this point carry their own GRANT beside their DDL
-- (see execution.fee_observations below). This block covers the three original tables only;
-- reading it as the complete grant set is what produced the 2026-09-04 gap.

-- ============================================================================
-- execution.fee_observations — what the BROKER says a trade costs.
-- ----------------------------------------------------------------------------
-- Added 2026-09-04. The canonical fee schedule
-- (quant-execution-engine .../reference/fee_schedule.toml) is a POLICY: a fixed,
-- deliberately conservative basis pinned at the most expensive tier so strategy
-- calculations are deterministic. This table holds the FACTS it is checked against.
--
-- 🔴 THE CHECK IS ONE-SIDED, and the asymmetry is the point:
--     observed <= basis  ->  normal (a promotion or a better tier). Record, no alert.
--     observed >  basis  ->  the conservative basis is no longer conservative, so every
--                            strategy calculation is UNDERSTATING cost. Alert + adopt.
-- Direction matters more than magnitude: a basis that is too expensive makes a strategy
-- look worse than it is and is safe; too cheap makes it look better, and in this umbrella
-- has already turned a losing result into an apparently positive one.
--
-- 🔴 TWO KINDS OF ROW, NEVER AVERAGED TOGETHER. `observation_kind` separates an
-- INDICATIVE QUOTE (what a hypothetical order WOULD cost) from a CHARGED amount (what a
-- real fill DID cost). They have different epistemic status; conflating them would let a
-- quote silently stand in for evidence. The blotter sweep that writes `charged` rows is
-- NOT built yet — this table is shaped so it lands without redesign.
--
-- 🔴 TIER DECLINE IS NOT DRIFT. Commission tiers accrue on MONTHLY volume, so an observed
-- rate that falls through a month and resets at the boundary is CORRECT BEHAVIOUR.
-- `fee_month` and `month_to_date_contracts` exist so alerting can compare like months at
-- like volume instead of reading a normal tier decline as a broken schedule.
-- ============================================================================

CREATE TABLE IF NOT EXISTS execution.fee_observations (
    id                      BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,

    observed_at             TIMESTAMPTZ  NOT NULL,
    observation_kind        TEXT         NOT NULL
        CHECK (observation_kind IN ('indicative_quote', 'charged')),
    source                  TEXT         NOT NULL,

    broker                  TEXT         NOT NULL,
    account                 TEXT         NOT NULL,

    -- Probe parameters. Fixed by reference/probe_order.toml so rows are comparable across
    -- days; stored per row anyway, because a definition that changed silently would other-
    -- wise be invisible in the series it produced.
    symbol                  TEXT         NOT NULL,
    contract_month          TEXT         NOT NULL,
    is_roll_boundary        BOOLEAN      NOT NULL DEFAULT FALSE,
    side                    TEXT         NOT NULL,
    quantity                INTEGER      NOT NULL CHECK (quantity > 0),
    price                   NUMERIC(18,5) NOT NULL CHECK (price >= 0),

    -- Parsed figures. NULL means "the source did not report it" — never zero.
    commission              NUMERIC(18,5),
    exchange_fee            NUMERIC(18,5),
    clearing_fee            NUMERIC(18,5),
    vat                     NUMERIC(18,5),
    total_fee               NUMERIC(18,5),

    -- Tier context: what makes a declining series legible as tiers rather than drift.
    fee_month               DATE         NOT NULL,
    month_to_date_contracts INTEGER,

    -- Everything the source returned, verbatim. The parsed columns above are an
    -- interpretation; this is the evidence, and it survives a parser being wrong.
    raw_response            JSONB        NOT NULL,

    -- The comparison outcome, stored so an alert can be reconstructed after the fact.
    basis_value             NUMERIC(18,5),
    basis_effective_from    DATE,
    verdict                 TEXT CHECK (verdict IN ('at_or_below', 'above')),

    inserted_at             TIMESTAMPTZ  NOT NULL DEFAULT now()
);

COMMENT ON TABLE execution.fee_observations IS
    'What the broker says a trade costs. Checked ONE-SIDEDLY against the canonical fee '
    'basis: observed<=basis is normal and silent; observed>basis alerts and is adopted as '
    'a new dated basis entry. Never averaged across observation_kind.';

CREATE INDEX IF NOT EXISTS fee_observations_month_idx
    ON execution.fee_observations (fee_month, symbol, observation_kind);
CREATE INDEX IF NOT EXISTS fee_observations_observed_at_idx
    ON execution.fee_observations (observed_at DESC);

-- 🔴 GRANT COLOCATED WITH THE TABLE, DELIBERATELY — this table was added BELOW the grants
-- block above and shipped with no grant at all (2026-09-04). CREATE TABLE runs as the
-- superuser, so `quant` got ZERO privileges, and `quant` querying information_schema would
-- then see NO TABLE AT ALL rather than a permission error: the gap presents as absence.
-- Keeping the grant next to its table makes forgetting it a single-location omission
-- instead of a cross-file one. `tests/test_schema_grants.py` enforces it.
--
-- SELECT, INSERT only — matching execution.fills and execution.order_events, NOT
-- execution.orders. Observations are evidence and the basis is an append-only dated series;
-- an observation that can be UPDATEd is not evidence. No sequence grant is needed: `id` is
-- GENERATED ALWAYS AS IDENTITY, whose sequence is internally linked and covered by INSERT.
GRANT SELECT, INSERT ON execution.fee_observations TO quant;
